# -*- coding: utf-8 -*-
"""q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sWpENZvgzgjxXKe7UwHMCkIOADHJz8w1
"""

import networkx as nx
import matplotlib.pyplot as plt
from networkx.algorithms.community.centrality import girvan_newman
import itertools
import time

def betweenness_clustering(G, k):
  old = time.time()
  gnc = girvan_newman(G)
  new = time.time()
  print("running time:", new-old)
  communities = list(itertools.takewhile(lambda c: len(c) <= k, gnc))[-1]
  print("modularity:", nx.algorithms.community.quality.modularity(G, communities))

dolphins_graph = nx.read_gml("dolphins.gml")
k = 4
betweenness_clustering(dolphins_graph, k)

karate_graph = nx.read_gml("karate.gml", label="id")
k = 3
betweenness_clustering(karate_graph, k)

jazz = nx.read_gml("jazz.gml")
k = 4
betweenness_clustering(jazz_graph, k)