# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OyMvcknSO0_aVqaCE6kNPAPYUOMwEmg0
"""

import networkx as nx
from networkx.algorithms.community.modularity_max import greedy_modularity_communities
import time

def modularity_clustering(G):
  old = time.time()
  communities = tuple(greedy_modularity_communities(G))
  new = time.time()
  print("running time:", new-old)
  print("num clusters:", len(communities))
  print("Modularity: " + str(nx.algorithms.community.modularity(G, communities)))

dolphins_graph = nx.read_gml("dolphins.gml")
modularity_clustering(dolphins_graph)

karate_graph = nx.read_gml("karate.gml", label="id")
modularity_clustering(karate_graph)

jazz_graph = nx.read_gml("jazz.gml")
modularity_clustering(jazz_graph)